include:
  - project.base.yml
name: LocalTypeless
settings:
  base:
    SWIFT_ACTIVE_COMPILATION_CONDITIONS: APPLE_SILICON_ENGINE
    ARCHS: arm64
packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: 0.13.0
  MLXSwiftExamples:
    url: https://github.com/ml-explore/mlx-swift-examples
    from: 2.25.0
targets:
  LocalTypeless:
    dependencies:
      - package: WhisperKit
      - package: MLXSwiftExamples
        product: MLXLLM
      - package: MLXSwiftExamples
        product: MLXLMCommon
